{{- if .Values.initializationFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-initialization
data:
{{- range $key, $val := .Values.initializationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}