{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  .env: |-
    {{- range $key, $value :=  .Values.env }}
    {{ $key }}={{ $value | quote }}
    {{- end }}
  pre-start.sh: |-
    #!/bin/bash
    cat /init/.env
    cp  /init/.env /app/
    cd /app/
    npm install
    npm run build
    cp -r dist/* /var/www/html
{{- end }}
---
{{- if .Values.param }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: param-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
  micro-service-config.js: |-
    {{- range $key, $value :=  .Values.param }}
    ${{ $key }}={{ $value | quote }}
    {{- end }}
{{- end }}