# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

teamId: postgresql
volume:
  size: 1Gi
numberOfInstances: 2 #实例数
postgresql:
  version: 12 #版本号，支持 9.6 10 11 12

resources:
  requests:
    memory: 100Mi
    cpu: 10m
  limits:
    memory: 800Mi
    cpu: 3000m
exporter: true

config: |-
  include 'postgresql.base.conf'
  archive_command = '/bin/true'
  archive_mode = 'on'
  archive_timeout = '1800s'
  autovacuum_analyze_scale_factor = '0.01'
  autovacuum_max_workers = '5'
  autovacuum_vacuum_scale_factor = '0.05'
  bg_mon.history_buckets = '120'
  bg_mon.listen_address = '0.0.0.0'
  checkpoint_completion_target = '0.9'
  cluster_name = 'postgresql-pgchr-mounttest'
  extwlist.custom_path = '/scripts'
  extwlist.extensions = 'btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,hypopg,timescaledb,pg_partman'
  hot_standby = 'on'
  listen_addresses = '*'
  log_autovacuum_min_duration = '0'
  log_checkpoints = 'on'
  log_connections = 'on'
  log_destination = 'csvlog'
  log_directory = '../pg_log'
  log_disconnections = 'on'
  log_file_mode = '0644'
  log_filename = 'postgresql-%u.log'
  log_line_prefix = '%t [%p]: [%l-1] %c %x %d %u %a %h '
  log_lock_waits = 'on'
  log_min_duration_statement = '500'
  log_rotation_age = '1d'
  log_statement = 'ddl'
  log_temp_files = '0'
  log_truncate_on_rotation = 'on'
  logging_collector = 'on'
  max_connections = '100'
  max_locks_per_transaction = '64'
  max_prepared_transactions = '0'
  max_replication_slots = '10'
  max_wal_senders = '10'
  max_worker_processes = '8'
  pg_stat_statements.track_utility = 'off'
  port = '5432'
  shared_buffers = '160MB'
  shared_preload_libraries = 'bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache'
  ssl = 'on'
  ssl_cert_file = '/run/certs/server.crt'
  ssl_key_file = '/run/certs/server.key'
  tcp_keepalives_idle = '900'
  tcp_keepalives_interval = '100'
  track_commit_timestamp = 'off'
  track_functions = 'all'
  wal_keep_segments = '8'
  wal_level = 'replica'
  wal_log_hints = 'on'
  hba_file = '/home/postgres/pgdata/pgroot/data/pg_hba.conf'
  ident_file = '/home/postgres/pgdata/pgroot/data/pg_ident.conf'
  
pgconfigyml: {}
#  |-
#  bootstrap:
#    dcs:
#      loop_wait: 10
#      maximum_lag_on_failover: 33554432
#      postgresql:
#        parameters:
#          archive_mode: 'on'
#          archive_timeout: 1800s
#          autovacuum_analyze_scale_factor: 0.02
#          autovacuum_max_workers: 5
#          autovacuum_vacuum_scale_factor: 0.05
#          checkpoint_completion_target: 0.9
#          hot_standby: 'on'
#          log_autovacuum_min_duration: 0
#          log_checkpoints: 'on'
#          log_connections: 'on'
#          log_disconnections: 'on'
#          log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
#          log_lock_waits: 'on'
#          log_min_duration_statement: 500
#          log_statement: ddl
#          log_temp_files: 0
#          max_connections: 100
#          max_replication_slots: 10
#          max_wal_senders: 10
#          tcp_keepalives_idle: 900
#          tcp_keepalives_interval: 100
#          track_functions: all
#          wal_keep_segments: 8
#          wal_level: hot_standby
#          wal_log_hints: 'on'
#        use_pg_rewind: true
#        use_slots: true
#      retry_timeout: 10
#      ttl: 30
#    initdb:
#    - auth-host: md5
#    - auth-local: trust
#    - encoding: UTF8
#    - locale: en_US.UTF-8
#    - data-checksums
#    post_init: /scripts/post_init.sh "zalandos"
#    users:
#      zalandos:
#        options:
#        - CREATEDB
#        - NOLOGIN
#        password: ''
#  kubernetes:
#    labels:
#      application: spilo
#    pod_ip: 0.0.0.0
#    ports:
#    - name: postgresql
#      port: 5432
#    role_label: spilo-role
#    scope_label: cluster-name
#    use_endpoints: true
#  postgresql:
#    authentication:
#      replication:
#        password: QWiFMm2aUj7YIRVw2Q167nWxPWQHothT27LZajJywrtNptdfOFE8mEy91LTrEUVH
#        username: standby
#      superuser:
#        password: oUET8sfmXW5Dz1zLXYYRA8knDY7wRjQFWZGZjup3chl5kC6Evjmz8Pri5m95jom1
#        username: postgres
#    basebackup_fast_xlog:
#      command: /scripts/basebackup.sh
#      retries: 2
#    bin_dir: /usr/lib/postgresql/12/bin
#    callbacks:
#      on_role_change: /scripts/on_role_change.sh zalandos true
#    connect_address: 0.0.0.0:5432
#    create_replica_method:
#    - basebackup_fast_xlog
#    data_dir: /home/postgres/pgdata/pgroot/data
#    listen: '*:5432'
#    name: postgresql-pgchr-mounttest-0
#    parameters:
#      archive_command: /bin/true
#      bg_mon.history_buckets: 120
#      bg_mon.listen_address: 0.0.0.0
#      extwlist.custom_path: /scripts
#      extwlist.extensions: btree_gin,btree_gist,citext,hstore,intarray,ltree,pgcrypto,pgq,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,hypopg,timescaledb,pg_partman
#      log_destination: csvlog
#      log_directory: ../pg_log
#      log_file_mode: '0644'
#      log_filename: postgresql-%u.log
#      log_rotation_age: 1d
#      log_truncate_on_rotation: 'on'
#      logging_collector: 'on'
#      pg_stat_statements.track_utility: 'off'
#      shared_buffers: 160MB
#      shared_preload_libraries: bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache
#      ssl: 'on'
#      ssl_cert_file: /run/certs/server.crt
#      ssl_key_file: /run/certs/server.key
#    pg_hba:
#    - local   all             all                                   trust
#    - hostssl all             +zalandos    127.0.0.1/32       pam
#    - host    all             all                127.0.0.1/32       md5
#    - hostssl all             +zalandos    ::1/128            pam
#    - host    all             all                ::1/128            md5
#    - hostssl replication     standby all                md5
#    - hostnossl all           all                all                reject
#    - hostssl all             +zalandos    all                pam
#    - hostssl all             all                all                md5
#    pgpass: /run/postgresql/pgpass
#    use_unix_socket: true
#  restapi:
#    connect_address: 0.0.0.0:8008
#    listen: :8008
#  scope: postgresql-pgchr-mounttest
