# Default values for ssdc-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: ctsi
imagePullSecrets: docker-local
env: {}
param: {}
nodeSelector: {}
resources:
  requests:
    memory: 100
    cpu: 250   
  limits:
    memory: 512
    cpu: 2048
web:
  image: ctsi/admin-project:1.0.0
  exporterImage: ctsi/nginx-vts-exporter:0.10.3
  imagePullPolicy: Always
  replicas: 1
  containerPort: 80
  exporterPort: 9913
circuitBreaker: 
  enabled: false
  consecutiveErrors: 1
  interval: 1s
  baseEjectionTime: 1m
  maxEjectionPercent: 100
currentLimiting: 
  enabled: false
  maxConnections: 100
  conetTimeout: 30ms
  tcpKeepalive: 
    time: 7200
    interval: 75s
loadBalancer: 
  enabled: false
  tpye: ROUND_ROBIN
timeout: 
  enabled: false
  time: 15s