# Default values for kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
elasticsearchRef: elasticsearch-test
image:
  repository: docker.elastic.co/kibana/kibana
  tag: 7.4.1

resources:
  requests:
    memory: 1000Mi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 2000m

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  enabled: true
#  kibanaPassword: i1M6L378N2o7m41BPdBAwrW3
exporter: 
  image: ctsi/kibana-prometheus-exporter:v7.5.x.1
