{{- if .Values.serviceMonitor.enabled }}
---
# Source: service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kibana.fullname" . }}-exporter
  labels:
    chart: {{ template "kibana.chart" . }}
    app: {{ template "kibana.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9684
      protocol: TCP
  selector:
    app: {{ template "kibana.name" . }}
    release: "{{ .Release.Name }}"
---
# Source: deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kibana.fullname" . }}-exporter
  labels:
    chart: {{ template "kibana.chart" . }}
    app: {{ template "kibana.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas:  1
  selector:
    matchLabels:
      app: {{ template "kibana.name" . }}
      release: "{{ .Release.Name }}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "kibana.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}-exporter
          image: "chamilad/kibana-prometheus-exporter:v7.5.x.1"
          imagePullPolicy: IfNotPresent
          env:
            {{ if .Values.serviceMonitor.kibanaPassword }}
            - name: kibanaPassword
              value: {{ .Values.serviceMonitor.kibanaPassword }}
              {{ else }}
            - name: kibanaPassword
              valueFrom:
                secretKeyRef:
                  key: elastic
                  name: {{ .Values.elasticsearchRef }}-es-elastic-user
              {{ end }}
          ports:
            - containerPort: 9684
              name: http
          command: ["/bin/kibana_exporter",
                    "-kibana.uri", "http://{{ .Release.Name }}-kb-http:5601",
                    "-kibana.username", "elastic",
                    "-kibana.password", "$(kibanaPassword)"]
---
# Source: serviceMonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "kibana.fullname" . }}-exporter
  labels:
    chart: {{ template "kibana.chart" . }}
    app: {{ template "kibana.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  endpoints:
    - interval: 15s
      port: http
      path: /metrics
      relabelings:
        - action: replace
          regex: (.*)
          sourceLabels:
            - __meta_kubernetes_service_label_release
          targetLabel: service
  selector:
    matchLabels:
      app: {{ template "kibana.name" . }}
      release: "{{ .Release.Name }}"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}