server:
  port: 9080
  servlet:
    session:
      timeout: PT24H #session超时时间设置
spring:
  profiles:
    active: mq
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: PaasConsole
  elasticsearch:
    rest:
      uris: http://10.64.15.86:9200
  datasource:
    #    qianbase
    #    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:qianbase://10.12.20.14:20158/defaultdb
    #    driver-class-name: org.qianbase.Driver
    #    username: hrbank
    #    password: hrbank10.114.14.40-
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   mysql
    url: jdbc:mysql://10.64.15.100:3306/paas_zhongzhai?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&serverTimezone=Hongkong
    #  ob
    #    url: jdbc:mysql://10.114.14.40:2881/mq_unit?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #url: jdbc:mysql://10.64.13.85:31570/paas4_container?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Esb#2021
  #    url: jdbc:mysql://10.114.10.220:3306/dap_paas?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  #    password: root123456
  #    高斯
  #      type: com.alibaba.druid.pool.DruidDataSource
  #      url: jdbc:postgresql://172.30.33.30:8000/dap?currentSchema=paas2022
  #      driver-class-name: org.postgresql.Driver
  #      username: root
  #      password: Abc1234!!
  #
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  favicon:
    enabled: false

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml,classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.apache.curator: warn
    org.apache.zookeeper: warn
    org.apache.kafka: warn
    org.springframework.aop.framework.CglibAopProxy: warn
    org.springframework.data.convert.CustomConversions: ERROR
    springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator: warn
    com.dap.paas.console: debug


# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: DAP PaaS
  application-version: 5.0
  application-description: DAP5.0API



#==== 定時任務=====
scheduler:
  ContainerAgentJob:
    cron: 0 0/1 * * * ?
  NodeStatusMonitorJob:
    cron: 0 0/1 * * * ?
  NodeMonitorJob:
    cron: 0 */1 * * * ?
  KafkaJob:
    cron: 0 0/1 * * * ?
  OverviewJob:
    cron: 0/30 * * * * ?
  RegisterTaskJob:
    cron: 0 0/2 * * * ?
  RocketTaskJob:
    cron: 15 */2 * * * ?
  RocketTopTaskJob:
    cron: 45 */5 * * * ?
  SdkStatusJob:
    cron: 0 */2 * * * ?
  SeqTimeJob:
    cron: 0 */2 * * * ?
  TruncateJob:
    cron: 0 0 0 * * ?
  ClientMonitorJob:
    cron: 0/20 * * * * ?
  BasicInfoSyncJob:
    #cron: 0/2 *  * * * ?
    cron: 0 0 */2 * * ?
  ConfigTimeJob:
    cron: 0/30 * * * * ?


  #==== 中债 加密平台扩展
config:
  encoder:
    requestUrl: http://127.0.0.1:9080/
    certDn: 20231112
    symAlg: sadsadqwe

dap:
  cache:
    container:
      monitorImage: 10.64.7.121:30085/paas/redis-exporter:1.0
      proxyImage: 10.64.7.121:30085/paas/predixy:1.0
      proxySecret: 123
      sshdImage: 10.64.7.121:30085/paas/sshd-sidecar:1.0
      secret: PaasRedis@2023!
  #==== 服务治理 推送配置=====
  gov:
    reg:
      connectString: http://127.0.0.1:9080/
      connectionTimeoutMs: 1000
      type: console
      envCode: dev
      console:
        publishUrl: ${dap.gov.reg.connectString}/v1/config/openApi/publish
        grayUrl: ${dap.gov.reg.connectString}/v1/config/openApi/grey
        globalPublishUrl: ${dap.gov.reg.connectString}/v1/config/openApi/global-publish
        grayOffLineUrl: ${dap.gov.reg.connectString}/v1/config/openApi/grey-offline
        detailUrl: ${dap.gov.reg.connectString}/v1/config/openApi/queryConfig
        offLineUrl: ${dap.gov.reg.connectString}/v1/config/openApi/config-offline
        configCount: ${dap.gov.reg.connectString}/v1/config/openApi/configCount
        deleteUrl: ${dap.gov.reg.connectString}/v1/config/openApi/delete
        clientIpListUrl: ${dap.gov.reg.connectString}/v1/config/openApi/getClientList
        environmentUrl: ${dap.gov.reg.connectString}/v1/config/openApi/getEnvList
        clientInstanceResult: ${dap.gov.reg.connectString}/v1/config/openApi/getClientInstanceResult

console:
  ip: 127.0.0.1
# 对接统一认证平台
gientech:
  initialDelay: 3000
  fixedRateString: 3000
  login:
    url: http://10.64.15.86:9002/login
  route:
    fromSystem: route_console
    locales: zh
    messageFile: route_console_msg.yml
    authorization:
      # 是否开启认证授权平台的token认证
      enabled: false
      # 审计日志
      audit-log:
        # 是否开启审计日志，默认是开启
        enabled: false
        # 审计日志上报地址
        log-url: http://22.21.112.56:9003/prod-api/api/open/monitor/operlog/add
      ucac:
        ucacUrl: http://10.64.15.86:9085
        ucacPath: /api/open/token/check
        appInfoPath: /api/open/data/app
        isUcac: false
        loginUrl: http://10.64.15.86:9002/login
  ucac-client:
    address: http://10.64.15.86:9002
#应用数据同步地址
dmc:
  dmcUrl: http://22.21.112.56:9003/prod-api/
  appinfo:
    accessid: a1d00843-36e4-4205-b9a1-00e2fd14f83d
    accessac: k4swlrfODAW8RGlHaphDo/uud05z4m3VuCo10VLVBnLSH:BnztBRxWVGx73BJci0ZKMHWGWCV1XZxdSPfTPQ==
    tenantid: default-tech
    appname: PaasConsole
    on-off: on

register:
  # 注册中心地址 可以填注册中心集群的虚拟ip或者是负载(非管控)
  registerCenterIp: 10.64.15.86
  # 对应registerCenterIp的端口
  registerCenterPort: 8848
  # 被调方技术组件名 管控提供
  tarComponentName: register
  #查询注册中心目录(域名或者ip是注册中心管控的)
  queryCatalogServices: http://10.64.15.86:8901/nacos/ns/catalog/services
  # 查询注册中心实例(域名或者ip是注册中心管控的)
  queryCatalogInstances: http://10.64.15.86:8901/nacos/ns/catalog/instances
  #注册中心反注册(域名或者ip是注册中心管控的)
  unRegisterUrl: http://10.64.15.86:8901/nacos/ns/instance
