com:
  dap:
    mq:
      # 消息sdk配置的数据源
      datasource:
        url: jdbc:mysql://10.114.14.65:3306/dap-paas-mq?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: Esb#2021
        driverClassName: com.mysql.cj.jdbc.Driver
        configLocation: classpath:mybatis-config.xml
      kafka:
        producer:
          switch: 'on'
        producers:
          - bootstrapServer: 10.114.14.66:6546
            groups:
              # 事务消息
              - groupName: kafka-p3
                sync: true
      rocketmq:
        messageModel: CLUSTERING
        producer:
          switch: 'on'
        producers:
          - namesrvAddr: 10.64.7.199:9886
            groups:
              # 事务消息
              - groupName: rocket-p1