apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-console
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name }}-console
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-console
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-name-server
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    name_service_cr: {{ .Release.Name }}-name-server
  ports:
    - port: 9876
      targetPort: 9876
      # use this port to access the name server cluster
