apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-console
  namespace: {{ .Release.Namespace | quote }}
spec:
  gateways:
  - biyi-gateway.istio-system
  hosts:
  - {{ .Release.Name }}.{{ .Values.domain }}
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-console
        port:
          number: 8080
