apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-app
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.java.replicas }} 
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
        release: {{ .Release.Name }}
      annotations: 
        sidecar.istio.io/inject: '{{ .Values.istio.enabled }}'
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.java.image }}
          imagePullPolicy: {{ .Values.java.imagePullPolicy }}
          resources:
            requests:
              memory: {{ cat .Values.resources.requests.memory "Mi"| nospace | quote}}
              cpu:  {{ cat .Values.resources.requests.cpu "m" | nospace | quote}}    
            limits:
              memory: {{ cat .Values.resources.limits.memory "Mi"| nospace | quote}}
              cpu:  {{ cat .Values.resources.limits.cpu "m" | nospace | quote}}
          ports:
          - containerPort: {{ .Values.java.containerPort }}   
          env:
          {{- range $key, $value :=  .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml .Values.nodeSelector | indent 2 }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets}}