{{- if .Values.service.clusterip.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clusterip-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-app
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.java.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.java.containerPort }}
      name: http-container
  selector:
    app: {{ .Release.Name }}-app
    release: {{ .Release.Name }}
{{- end }}