{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: networkpolicy-{{ .Release.Name }}
  namespace: {{ template "zookeeper.namespace" . }}
  # 配置仅当前命名空间服务可以访问
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
  ingress: 
  - from:
    - podSelector: {}
    - namespaceSelector: {}
{{-end}}