apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - biyi-gateway.istio-system
  hosts:
  - {{ .Release.Name }}.{{ .Values.domain }}
  http:
  {{- if .Values.vs.cookieMatch.enabled }}
  - match:
    - headers:
        cookie:
          regex: {{ .Values.vs.cookieMatch.cookieRegex }}
    route:
    - destination:
        host: {{ .Values.vs.cookieMatch.outsideHost }}
        port:
          number: {{ .Values.vs.cookieMatch.outsideContainerPort }}
  {{- end }}
  - route:
    - destination:
        host: {{ .Release.Name }}-service
    {{- if .Values.timeout.enabled }}
    #超时
    timeout: {{ .Values.timeout.time }}
    {{- end -}}
