{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mysql.fullname" . }}
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      relabelings:
        - action: replace
          regex: (.*)
          sourceLabels:
            - __meta_kubernetes_service_label_release
          targetLabel: service
      interval: 60s
      metricRelabelings:
        - action: drop
          regex: mysql_(perf_schema_file_instances_total|perf_schema_table_io_waits_total|perf_schema_table_io_waits_seconds_total|perf_schema_sql_lock_waits_seconds_total|perf_schema_file_events_seconds_total|info_schema_threads|info_schema_threads_seconds|perf_schema_index_io_waits_total|perf_schema_events_waits_total|perf_schema_events_waits_seconds_total|perf_schema_file_events_total|perf_schema_sql_lock_waits_total|perf_schema_file_events_bytes_total|perf_schema_index_io_waits_seconds_total|perf_schema_file_instances_bytes)
          sourceLabels:
          - __name__
  selector:
    matchLabels:
      app: {{ include "mysql.fullname" . }}
      release: {{ .Release.Name }}
{{- end }}
