apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
  version: {{ .Values.image.tag }}
  count: {{ .Values.replicaCount }}
  elasticsearchRef:
    name: {{ .Values.elasticsearchRef }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true  
  podTemplate:
    metadata:
      labels:
        release: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "false"   
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory| nospace | quote}}
            cpu:  {{ .Values.resources.requests.cpu | nospace | quote}} 
          limits:
            memory: {{ .Values.resources.limits.memory| nospace | quote}}
            cpu:  {{ .Values.resources.limits.cpu | nospace | quote}}