---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-app
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.web.containerPort }}
      name: http-container
    - port: {{ .Values.web.exporterPort }}
      protocol: TCP
      targetPort: {{ .Values.web.exporterPort }}
      name: http-exporter
  selector:
    app: {{ .Release.Name }}-app
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-app
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
        release: {{ .Release.Name }}
        {{- if .Values.logCollect }}
        log-collect: "true"
        {{- end }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
{{- if .Values.serviceMonitor.enabled}}
      - name: {{ .Release.Name }}-exporter
        image:  {{ .Values.web.exporterImage }}
        imagePullPolicy: {{ .Values.web.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.web.exporterPort }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
{{- end }}
      - name: {{ .Release.Name }}-app
        image: {{ .Values.web.image }}
        imagePullPolicy: {{ .Values.web.imagePullPolicy }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.web.containerPort }}
        volumeMounts:
        {{- if .Values.param }}
        - name: param
          mountPath: /usr/share/nginx/html/configs/micro-service-config.js
          subPath: micro-service-config.js
        {{- end}}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets}}
      volumes:
      {{- if .Values.param }}
      - name: param
        configMap:
          name: param-{{ .Release.Name }}
      {{- end }}
---
{{- if .Values.serviceMonitor.enabled}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: {{ .Release.Name }}-app
    release: {{ .Release.Name }}
  name:  {{ .Release.Name }}-app-monitor
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: http-exporter
    relabelings:
      - action: replace
        regex: (.*)
        sourceLabels:
          - __meta_kubernetes_service_label_release
        targetLabel: service
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
      release: {{ .Release.Name }}
{{- end}}