server:
  port: 8089

####序列SDK相关配置
dap:
  #序列配置
  sequence:
     #sdk名称
    clientName: seq-demo
     # 集群名称
    seqClusterName: seq-cluster
     # 集群下所有server的地址信息
#    urls: 10.64.13.36:8111
    urls: 127.0.0.1:8111
    #workerId: 001
    consoleUrl: 127.0.0.1:9081

spring:
  application:
    name: paas4-seq-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-interval: 30s
        health-check-timeout: 5s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    river-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.64.13.31:6308/seq_demo?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root123456
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
