apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}-exporter
  labels:
    chart: {{ template "elasticsearch.chart" . }}-exporter
    app: {{ template "elasticsearch.name" . }}-exporter
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9108
      protocol: TCP
  selector:
    app: {{ template "elasticsearch.name" . }}-exporter
    release: "{{ .Release.Name }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "elasticsearch.fullname" . }}-exporter
  labels:
    chart: {{ template "elasticsearch.chart" . }}-exporter
    app: {{ template "elasticsearch.name" . }}-exporter
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas:  1
  selector: 
    matchLabels:
      app: {{ template "elasticsearch.name" . }}-exporter
      release: "{{ .Release.Name }}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch.name" . }}-exporter
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: elastic
              valueFrom: 
                secretKeyRef:
                  key: elastic
                  name: {{ .Release.Name }}-es-elastic-user
          image:  {{ .Values.exporter.image }}
          imagePullPolicy: IfNotPresent
          command: ["elasticsearch_exporter",
                    "--es.all",
                    "--es.indices",
                    "--es.indices_settings",
                    "--es.shards",
                    "--es.snapshots",
                    "--es.cluster_settings",
                    "--es.uri=http://elastic:$(elastic)@{{ .Release.Name }}-es-http:9200",
                    "--es.timeout=30s",
                    "--web.listen-address=:9108",
                    "--web.telemetry-path=/metrics"]
          ports:
            - containerPort: 9108
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 5
     
{{- if .Values.exporter.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "elasticsearch.fullname" . }}-exporter
  namespace:  {{ .Release.Namespace | quote }}
  labels:
    chart: {{ template "elasticsearch.chart" . }}-exporter
    app: {{ template "elasticsearch.name" . }}-exporter
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  endpoints:
  - interval: 60s
    scrapeTimeout: 10s
    honorLabels: true
    port: http
    path:  /metrics
    relabelings:
      - action: replace
        regex: (.*)
        sourceLabels:
          - __meta_kubernetes_service_label_release
        targetLabel: service
    scheme: http
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      app: {{ template "elasticsearch.name" . }}-exporter
      release: "{{ .Release.Name }}"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
