{{- if .Values.ingress.enabled }}
{{- $fullName := include "minio.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Release.Namespace | quote }}
spec:
  gateways:
  - biyi-gateway.istio-system
  hosts:
  - {{ .Release.Name }}.{{ .Values.domain }}
  http:
  - route:
    - destination:
        host: {{ $fullName }}
{{- end }}