{{- if .Values.blackWhiteList.enabled }}
apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-policy
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  action: {{ .Values.blackWhiteList.type }}
  rules:
  - from:
    - source:
        namespaces: 
        {{- range .Values.blackWhiteList.list }}
        - {{ .value }}
        {{- end -}}
{{- end -}}
