apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
#  tls:
#    - hosts:
#      - api.ctsi.ingress.ssdc.solutions
#      - web.ctsi.ingress.ssdc.solutions
#      secretName:  tls-ingress-secret  
#      namespace: {{ .Values.namespace }}
  rules:
    - host: {{ .Release.Name }}.ingress.ssdc.solutions
      http:
        paths:
          - backend:
              namespace: {{ .Values.namespace }}
              serviceName: {{ .Release.Name }}-service
              servicePort: {{ .Values.java.containerPort }}
            path: /
    - host: {{ .Release.Name }}.ingress.ctbiyi.com
      http:
        paths:
          - backend:
              namespace: {{ .Values.namespace }}
              serviceName: {{ .Release.Name }}-service
              servicePort: {{ .Values.java.containerPort }}
            path: /
