{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "redis-ha.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.metrics.service.annotations }}
  annotations: {{ toYaml .Values.metrics.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  {{ if eq .Values.metrics.service.type "LoadBalancer" -}} {{ if .Values.metrics.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.metrics.service.loadBalancerIP }}
  {{ end -}}
  {{- end -}}
  ports:
  - name: metrics
    port: 9121
    targetPort: metrics
  selector:
    name: {{ template "redis-ha.fullname" . }}-server
{{- end }}
