# Default values for ssdc-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
imagePullSecrets: docker-local
env: {}
nodeSelector: {}
resources:
  requests: { }
  limits: { }
java:
  image: xty-group/xtydemoapi:1.0.0
  imagePullPolicy: Always
  replicas: 1
  containerPort: 9000
  javaOpts: 
circuitBreaker: 
  enabled: false
  consecutiveErrors: 1
  interval: 1s
  baseEjectionTime: 1m
  maxEjectionPercent: 100
currentLimiting: 
  enabled: false
  maxConnections: 100
  conetTimeout: 30ms
  tcpKeepalive: 
    time: 7200s
    interval: 75s
  httpHttp1MaxPendingRequests: 1000
  httpMaxRequestsPerConnection: 10
loadBalancer: 
  enabled: false
  type: ROUND_ROBIN
timeout: 
  enabled: false
  time: 15s
blackWhiteList:
  enabled: false
  type: ALLOW
  list: []
skywalking:
  enabled: false
  image: ctsi/skywalking-agent:1.1.0N
  collector: 192.168.152.45:32232
monitor:
  enabled: false
domain: entry.ctbiyi.com
vs:
  cookieMatch:
    enabled: false
    outsideHost: code-app-svc
    outsideContainerPort: 9000
    cookieRegex: ^(.*?; ?)?(version=code-server)(;.*)?$
logCollect: false
useGpu: false
nodeAffinityPreset:
  nodeSelectorTerms:
    nvidiaComCudaDriverMajor: '455'
    nvidiaComCudaDriverMinor: '06'
    nvidiaComFamily: ampere
