apiVersion: v1
kind: Service
metadata:
  name: yiyan-license-service
spec:
  selector:
    name: yiyan-license-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
  type: ClusterIP
