apiVersion: v1
appVersion: RELEASE.2019-08-07T01-59-21Z
description: Offical chart version:2.5.16
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: hello@acale.ph
  name: Acaleph
- email: dev@minio.io
  name: Minio
name: minio
sources:
- https://github.com/minio/minio
version: 22.3.1
